In [1]:
import os
import cv2
import pandas as pd

In [2]:
image_path = 'Sukuna.jpg'
if not os.path.exists(image_path):
    raise FileNotFoundError(f"{image_path} does not exist")
img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img.shape

(194, 259, 3)

In [3]:
r, g, b = img[:, :, 0].flatten(), img[:, :, 1].flatten(), img[:, :, 2].flatten()

df = pd.DataFrame({'Red': r, 'Green': g, 'Blue': b})
df.head()

   Red  Green  Blue
0   42     41    59
1   42     41    59
2   42     41    59
3   42     41    59
4   42     41    59

In [4]:
df.describe()

                Red         Green          Blue
count  50246.000000  50246.000000  50246.000000
mean     102.265235     76.778848     64.153405
std       56.695471     48.123796     32.751688
min        0.000000      0.000000      0.000000
25%       45.000000     30.000000     35.000000
50%      111.000000     81.000000     63.000000
75%      146.000000    110.000000     83.000000
max      255.000000    241.000000    230.000000